title: "Ash Parajuli"
description: "Somewhere to share my thoughts and projects."
author: Ash Parajuli
url: "https://amparaj.github.io"
theme: jekyll-theme-minimal
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag

social:
  github: amparaj
  linkedin: amparajuli

kramdown:
  input: GFM
  syntax_highlighter: rouge
