title: "Ayush Parajuli"
description: "Travel demand modeller in Brisbane, writing about transport modelling, Python, machine learning and side projects."
author: Ayush Parajuli
url: "https://amparaj.github.io"
theme: jekyll-theme-minimal
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag

social:
  github: amparaj
  linkedin: amparajuli

kramdown:
  input: GFM
  syntax_highlighter: rouge
